# start site locally: jekyll serve --config _config.yml,_config_dev.yml

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EAMLI
email: hello@eamli.com
description: >- # this means to ignore newlines until "baseurl:"
  EAMLI generates rapid full financial forecasts, discounted cash-flows, scenario based modelling and valuations.  Ideally suited for startup or scaleup valuations.
baseurl: "/some_website" # the subpath of your site, e.g. /blog
url: "//github.com/elliotte/some_website" 
linkedin_username: eamli
github_username:  eamli
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# start site locally: jekyll serve --config _config.yml,_config_dev.yml
